[package]
name = "player-platform"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
raw-window-handle = "0.6"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Graphics_Gdi", "Win32_System_Registry", "Win32_Graphics_Dwm", "Win32_UI_WindowsAndMessaging"] }

[target.'cfg(not(windows))'.dependencies]
fontdb = { version = "=0.23.0", default-features = false, features = ["std", "fs"] }
