#[derive(Clone, Debug)]
pub struct MediaPreview {
    pub id: i32,
    pub title: String,
    pub artist: String,
    pub collection: String,
    pub duration: String,
    pub cover: i32,
    pub artwork: slint::Image,
}

#[derive(Clone, Debug, Default)]
pub struct ShellViewModel {
    pub audio: AudioViewModel,
    pub fonts: FontViewModel,
    pub column_song: f32,
    pub column_artist: f32,
    pub window_controls_left: bool,
    pub library: LibraryViewModel,
    pub video_library: LibraryViewModel,
    pub video_renderer_requested: bool,
    pub can_resume_video: bool,
    pub search_query: String,
    pub appearance: AppearanceViewModel,
    pub page: i32,
    pub selected_id: i32,
    pub selected_title: String,
    pub selected_artist: String,
    pub selected_duration: String,
    pub selected_cover: i32,
    pub volume_percent: f32,
    pub favorite: bool,
    pub status: String,
    pub status_revision: u64,
    pub tracks: std::rc::Rc<Vec<MediaPreview>>,
    pub queue: std::rc::Rc<Vec<MediaPreview>>,
    pub queue_revision: u64,
    pub recent: Vec<MediaPreview>,
    pub playing: bool,
    pub has_media: bool,
    pub has_video: bool,
    pub position_text: String,
    pub progress: f32,
    pub seekable: bool,
    pub muted: bool,
    pub speed_index: i32,
    pub speed_choices: Vec<String>,
    pub info: String,
    pub device_names: Vec<String>,
    pub device_index: i32,
    pub audio_tracks: Vec<String>,
    pub audio_index: i32,
    pub subtitle_tracks: Vec<String>,
    pub subtitle_index: i32,
    pub chapters: Vec<String>,
    pub panel_open: bool,
    pub fullscreen: bool,
    pub window_mode: i32,
    pub decode_mode: i32,
    pub decode_threads: i32,
    pub deinterlace: bool,
    pub deband: bool,
    pub decode_scope: i32,
    pub decode_origin: String,
    pub short_bindings: Vec<(String, String)>,
    pub seek_step: i32,
    pub volume_step: i32,
    pub hold_ms: i32,
    pub hold_speed: String,
    pub settings_revision: u64,
}

#[derive(Clone, Debug, Default)]
pub struct AudioViewModel {
    pub preview: bool,
    pub cover: slint::Image,
    pub asset_revision: u64,
    pub lyrics: std::rc::Rc<Vec<(String, i32)>>,
    pub plain_lyrics: std::rc::Rc<String>,
    pub active_lyric: i32,
    pub album: String,
    pub status: String,
    pub origin: String,
    pub mode: i32,
    pub preserve_rate: bool,
    pub offset_ms: i32,
    pub eq_scope: i32,
    pub eq_name: String,
    pub eq_enabled: bool,
    pub preamp: String,
    pub auto_headroom: bool,
    pub headroom: String,
    pub bands: Vec<(String, f32, String, i32)>,
    pub presets: Vec<String>,
    pub preset_index: i32,
    pub binding: String,
}

#[derive(Clone, Debug, Default)]
pub struct LibraryViewModel {
    pub rows: std::rc::Rc<Vec<MediaPreview>>,
    pub revision: u64,
    pub folders: Vec<String>,
    pub folder: i32,
    pub busy: bool,
    pub message: String,
    pub selected: i32,
}
#[derive(Clone, Debug)]
pub struct AppearanceViewModel {
    pub design: i32,
    pub scheme: i32,
    pub dark: bool,
    pub accent: u32,
    pub ink: u32,
    pub accent_text: u32,
    pub system_accent: bool,
    pub custom_accent: String,
    pub reduce_motion: bool,
    pub os_reduce_motion: bool,
    pub system_available: bool,
    pub library_background_style: i32,
    pub library_background_opacity: i32,
    pub library_background_blur: i32,
    pub library_background_name: String,
    pub lyrics_background_style: i32,
    pub lyrics_background_opacity: i32,
    pub lyrics_background_blur: i32,
    pub lyrics_background_name: String,
    pub custom_library_background: slint::Image,
    pub custom_lyrics_background: slint::Image,
    pub background_image_revision: u64,
}
impl Default for AppearanceViewModel {
    fn default() -> Self {
        Self {
            design: 1,
            scheme: 0,
            dark: true,
            accent: 0x6875e8,
            ink: 0xffffff,
            accent_text: 0x9fa8ff,
            system_accent: true,
            custom_accent: "#6875e8".into(),
            reduce_motion: false,
            os_reduce_motion: false,
            system_available: false,
            library_background_style: 0,
            library_background_opacity: 35,
            library_background_blur: 0,
            library_background_name: String::new(),
            lyrics_background_style: 0,
            lyrics_background_opacity: 35,
            lyrics_background_blur: 0,
            lyrics_background_name: String::new(),
            custom_library_background: Default::default(),
            custom_lyrics_background: Default::default(),
            background_image_revision: 0,
        }
    }
}

#[derive(Clone, Debug, Default)]
pub struct FontViewModel {
    pub revision: u64,
    pub names: std::rc::Rc<Vec<String>>,
    pub ui: String,
    pub lyrics: String,
    pub ui_index: i32,
    pub lyrics_index: i32,
    pub subtitle_index: i32,
    pub override_ass: bool,
    pub busy: bool,
    pub message: String,
}
