#[derive(Clone, Debug)]
pub struct MediaPreview {
    pub id: i32,
    pub title: String,
    pub artist: String,
    pub collection: String,
    pub duration: String,
    pub cover: i32,
}

#[derive(Clone, Debug, Default)]
pub struct ShellViewModel {
    pub page: i32,
    pub selected_id: i32,
    pub selected_title: String,
    pub selected_artist: String,
    pub selected_duration: String,
    pub selected_cover: i32,
    pub volume_percent: f32,
    pub favorite: bool,
    pub status: String,
    pub status_revision: u64,
    pub tracks: Vec<MediaPreview>,
    pub queue: Vec<MediaPreview>,
    pub recent: Vec<MediaPreview>,
    pub playing: bool,
    pub has_media: bool,
    pub has_video: bool,
    pub position_text: String,
    pub progress: f32,
    pub seekable: bool,
    pub muted: bool,
    pub speed_index: i32,
    pub speed_choices: Vec<String>,
    pub info: String,
    pub device_names: Vec<String>,
    pub device_index: i32,
    pub audio_tracks: Vec<String>,
    pub audio_index: i32,
    pub subtitle_tracks: Vec<String>,
    pub subtitle_index: i32,
    pub chapters: Vec<String>,
    pub panel_open: bool,
    pub fullscreen: bool,
    pub window_mode: i32,
    pub decode_mode: i32,
    pub decode_threads: i32,
    pub deinterlace: bool,
    pub deband: bool,
    pub decode_scope: i32,
    pub decode_origin: String,
    pub short_bindings: Vec<(String, String)>,
    pub seek_step: i32,
    pub volume_step: i32,
    pub hold_ms: i32,
    pub hold_speed: String,
    pub settings_revision: u64,
}
